function RussianLetters({ onBack, onLessonSelect }) {

  const lessons = [
    {
      id: 1,
      letter: "А",
      title: "Изучаем букву А",
      description: "Первая буква русского алфавита - А",
      words: ["Арбуз", "Автобус", "Акула", "Ананас"],
      images: ["🍉", "🚌", "🦈", "🍍", "✈️", "🚗", "🏠", "📚", "⭐", "🎨"],
      activity: "Найдите русские слова на букву А",
      letterImage: "🍉",
      bgColor: 'bg-red-100 hover:bg-red-200',
      iconBg: 'bg-red-400',
      textColor: 'text-red-800',
      borderColor: 'border-red-200',
    },
    {
      id: 2,
      letter: "Б",
      title: "Изучаем букву Б",
      description: "Вторая буква русского алфавита - Б",
      words: ["Банан", "Белка", "Бабочка", "Барабан"],
      images: ["🍌", "🐿️", "🦋", "🥁", "🐻", "⚽", "📖", "🎈", "🔔", "🚲"],
      activity: "Посчитайте предметы на букву Б",
      letterImage: "🍌",
      bgColor: 'bg-blue-100 hover:bg-blue-200',
      iconBg: 'bg-blue-400',
      textColor: 'text-blue-800',
      borderColor: 'border-blue-200',
    },
    {
      id: 3,
      letter: "В",
      title: "Изучаем букву В",
      description: "Третья буква русского алфавита - В",
      words: ["Волк", "Ворон", "Велосипед", "Вода"],
      images: ["🐺", "🐦‍⬛", "🚲", "💧", "🌸", "🎯", "💎", "🥛", "🌊", "🌟"],
      activity: "Найдите предметы на букву В",
      letterImage: "🐺",
      bgColor: 'bg-green-100 hover:bg-green-200',
      iconBg: 'bg-green-400',
      textColor: 'text-green-800',
      borderColor: 'border-green-200',
    },
    {
      id: 4,
      letter: "Г",
      title: "Изучаем букву Г",
      description: "Четвертая буква русского алфавита - Г",
      words: ["Гусь", "Гриб", "Голубь", "Гитара"],
      images: ["🦢", "🍄", "🕊️", "🎸", "🦌", "🍎", "👁️", "🎭", "⚡", "🏠"],
      activity: "Найдите животных и предметы на букву Г",
      letterImage: "🦢",
      bgColor: 'bg-yellow-100 hover:bg-yellow-200',
      iconBg: 'bg-yellow-400',
      textColor: 'text-yellow-800',
      borderColor: 'border-yellow-200',
    },
    {
      id: 5,
      letter: "Д",
      title: "Изучаем букву Д",
      description: "Пятая буква русского алфавита - Д",
      words: ["Дом", "Дерево", "Дракон", "Дождь"],
      images: ["🏠", "🌳", "🐲", "🌧️", "🦅", "🍎", "⚡", "🎭", "🌍", "🏞️"],
      activity: "Изучайте природу и здания на букву Д",
      letterImage: "🏠",
      bgColor: 'bg-purple-100 hover:bg-purple-200',
      iconBg: 'bg-purple-400',
      textColor: 'text-purple-800',
      borderColor: 'border-purple-200',
    },
    {
      id: 6,
      letter: "Е",
      title: "Изучаем букву Е",
      description: "Шестая буква русского алфавита - Е",
      words: ["Енот", "Ель", "Единорог", "Еж"],
      images: ["🦝", "🎄", "🦄", "🦔", "🍓", "🎪", "📷", "⚽", "🦋", "🌈"],
      activity: "ЕНайдите предметы на эту букву",
      letterImage: "🦝",
      bgColor: 'bg-pink-100 hover:bg-pink-200',
      iconBg: 'bg-pink-400',
      textColor: 'text-pink-800',
      borderColor: 'border-pink-200',
    },
    {
      id: 7,
      letter: "Ё",
      title: "Изучаем букву Ё",
      description: "Седьмая буква русского алфавита - Ё",
      words: ["Ёж", "Ёлка", "Ёршик", "Ёмкость"],
      images: ["🦔", "🎄", "🧽", "🪣", "🍇", "🎸", "🌍", "⚙️", "🎯", "🦒"],
      activity: "ЁНайдите предметы на эту букву",
      letterImage: "🦔",
      bgColor: 'bg-indigo-100 hover:bg-indigo-200',
      iconBg: 'bg-indigo-400',
      textColor: 'text-indigo-800',
      borderColor: 'border-indigo-200',
    },
    {
      id: 8,
      letter: "Ж",
      title: "Изучаем букву Ж",
      description: "Восьмая буква русского алфавита - Ж",
      words: ["Жук", "Жираф", "Жаба", "Желтый"],
      images: ["🪲", "🦒", "🐸", "💛", "🍯", "🎵", "📦", "🌎", "ℹ️", "🎆"],
      activity: "ЖНайдите предметы на эту букву",
      letterImage: "🪲",
      bgColor: 'bg-teal-100 hover:bg-teal-200',
      iconBg: 'bg-teal-400',
      textColor: 'text-teal-800',
      borderColor: 'border-teal-200',
    },
    {
      id: 9,
      letter: "З",
      title: "Изучаем букву З",
      description: "Девятая буква русского алфавита - З",
      words: ["Заяц", "Змея", "Зонт", "Звезда"],
      images: ["🐰", "🐍", "☂️", "⭐", "🍿", "💪", "✨", "🧘", "🌈", "🎆"],
      activity: "ЗНайдите предметы на эту букву",
      letterImage: "🐰",
      bgColor: 'bg-cyan-100 hover:bg-cyan-200',
      iconBg: 'bg-cyan-400',
      textColor: 'text-cyan-800',
      borderColor: 'border-cyan-200',
    },
    {
      id: 10,
      letter: "И",
      title: "Изучаем букву И",
      description: "Десятая буква русского алфавита - И",
      words: ["Игра", "Игла", "Индюк", "Изюм"],
      images: ["🎮", "📌", "🦃", "🍇", "💎", "🗝️", "🏆", "🥝", "🎂", "🎨"],
      activity: "ИНайдите предметы на эту букву",
      letterImage: "🎮",
      bgColor: 'bg-orange-100 hover:bg-orange-200',
      iconBg: 'bg-orange-400',
      textColor: 'text-orange-800',
      borderColor: 'border-orange-200',
    },
    {
      id: 11,
      letter: "Й",
      title: "Изучаем букву Й",
      description: "Буква русского алфавита - Й",
      words: ["Йогурт", "Йод", "Йога", "Йети"],
      images: ["🥛", "🩹", "🧘", "🦣", "🥝", "📚", "🔍", "🎆", "✨", "💕"],
      activity: "ЙНайдите предметы на эту букву",
      letterImage: "🥛",
      bgColor: 'bg-lime-100 hover:bg-lime-200',
      iconBg: 'bg-lime-400',
      textColor: 'text-lime-800',
      borderColor: 'border-lime-200',
    },
    {
      id: 12,
      letter: "К",
      title: "Изучаем букву К",
      description: "Буква русского алфавита - К",
      words: ["Кот", "Корова", "Книга", "Кукла"],
      images: ["🐱", "🐄", "📚", "🪆", "🐵", "🎵", "🌙", "💪", "👐", "🏆"],
      activity: "КНайдите предметы на эту букву",
      letterImage: "🐱",
      bgColor: 'bg-emerald-100 hover:bg-emerald-200',
      iconBg: 'bg-emerald-400',
      textColor: 'text-emerald-800',
      borderColor: 'border-emerald-200',
    },
    {
      id: 13,
      letter: "Л",
      title: "Изучаем букву Л",
      description: "Буква русского алфавита - Л",
      words: ["Лев", "Лошадь", "Лимон", "Лодка"],
      images: ["🦁", "🐴", "🍋", "⛵", "🎶", "🎆", "📚", "🌙", "🐟", "🎯"],
      activity: "ЛНайдите предметы на эту букву",
      letterImage: "🦁",
      bgColor: 'bg-violet-100 hover:bg-violet-200',
      iconBg: 'bg-violet-400',
      textColor: 'text-violet-800',
      borderColor: 'border-violet-200',
    },
    {
      id: 14,
      letter: "М",
      title: "Изучаем букву М",
      description: "Буква русского алфавита - М",
      words: ["Медведь", "Молоко", "Мяч", "Машина"],
      images: ["🐻", "🥛", "⚽", "🚗", "🌊", "🌟", "🎵", "🎆", "📚", "☀️"],
      activity: "МНайдите предметы на эту букву",
      letterImage: "🐻",
      bgColor: 'bg-sky-100 hover:bg-sky-200',
      iconBg: 'bg-sky-400',
      textColor: 'text-sky-800',
      borderColor: 'border-sky-200',
    },
    {
      id: 15,
      letter: "Н",
      title: "Изучаем букву Н",
      description: "Буква русского алфавита - Н",
      words: ["Носорог", "Ножницы", "Нос", "Небо"],
      images: ["🦏", "✂️", "👃", "☁️", "🐂", "🍕", "📷", "🎆", "💪", "🎭"],
      activity: "ННайдите предметы на эту букву",
      letterImage: "🦏",
      bgColor: 'bg-rose-100 hover:bg-rose-200',
      iconBg: 'bg-rose-400',
      textColor: 'text-rose-800',
      borderColor: 'border-rose-200',
    },
    {
      id: 16,
      letter: "О",
      title: "Изучаем букву О",
      description: "Буква русского алфавита - О",
      words: ["Олень", "Окно", "Облако", "Огонь"],
      images: ["🦌", "🪟", "☁️", "🔥", "🌹", "📚", "🚗", "🏆", "🎆", "✨"],
      activity: "ОНайдите предметы на эту букву",
      letterImage: "🦌",
      bgColor: 'bg-amber-100 hover:bg-amber-200',
      iconBg: 'bg-amber-400',
      textColor: 'text-amber-800',
      borderColor: 'border-amber-200',
    },
    {
      id: 17,
      letter: "П",
      title: "Изучаем букву П",
      description: "Буква русского алфавита - П",
      words: ["Петух", "Паук", "Пингвин", "Пицца"],
      images: ["🐓", "🕷️", "🐧", "🍕", "🔴", "🚀", "🏆", "📚", "✨", "🎵"],
      activity: "ПНайдите предметы на эту букву",
      letterImage: "🐓",
      bgColor: 'bg-red-100 hover:bg-red-200',
      iconBg: 'bg-red-500',
      textColor: 'text-red-800',
      borderColor: 'border-red-200',
    },
    {
      id: 18,
      letter: "Р",
      title: "Изучаем букву Р",
      description: "Буква русского алфавита - Р",
      words: ["Рыба", "Робот", "Радуга", "Ракета"],
      images: ["🐟", "🤖", "🌈", "🚀", "☀️", "🏊", "🎆", "🎨", "📚", "✨"],
      activity: "РНайдите предметы на эту букву",
      letterImage: "🐟",
      bgColor: 'bg-blue-100 hover:bg-blue-200',
      iconBg: 'bg-blue-500',
      textColor: 'text-blue-800',
      borderColor: 'border-blue-200',
    },
    {
      id: 19,
      letter: "С",
      title: "Изучаем букву С",
      description: "Буква русского алфавита - С",
      words: ["Солнце", "Собака", "Слон", "Самолет"],
      images: ["☀️", "🐕", "🐘", "✈️", "🚗", "🚂", "🐅", "🎯", "🎆", "✨"],
      activity: "СНайдите предметы на эту букву",
      letterImage: "☀️",
      bgColor: 'bg-green-100 hover:bg-green-200',
      iconBg: 'bg-green-500',
      textColor: 'text-green-800',
      borderColor: 'border-green-200',
    },
    {
      id: 20,
      letter: "Т",
      title: "Изучаем букву Т",
      description: "Буква русского алфавита - Т",
      words: ["Тигр", "Телефон", "Торт", "Туча"],
      images: ["🐅", "📞", "🎂", "☁️", "🦄", "🎆", "📚", "✨", "🎭", "🎨"],
      activity: "ТНайдите предметы на эту букву",
      letterImage: "🐅",
      bgColor: 'bg-yellow-100 hover:bg-yellow-200',
      iconBg: 'bg-yellow-500',
      textColor: 'text-yellow-800',
      borderColor: 'border-yellow-200',
    },
    {
      id: 21,
      letter: "У",
      title: "Изучаем букву У",
      description: "Буква русского алфавита - У",
      words: ["Утка", "Улитка", "Удочка", "Утро"],
      images: ["🦆", "🐌", "🎣", "🌅", "🎨", "🎆", "📚", "✨", "🎭", "🏆"],
      activity: "УНайдите предметы на эту букву",
      letterImage: "🦆",
      bgColor: 'bg-purple-100 hover:bg-purple-200',
      iconBg: 'bg-purple-500',
      textColor: 'text-purple-800',
      borderColor: 'border-purple-200',
    },
    {
      id: 22,
      letter: "Ф",
      title: "Изучаем букву Ф",
      description: "Буква русского алфавита - Ф",
      words: ["Фламинго", "Фонарь", "Флаг", "Фрукт"],
      images: ["🦩", "🔦", "🏁", "🍎", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "ФНайдите предметы на эту букву",
      letterImage: "🦩",
      bgColor: 'bg-pink-100 hover:bg-pink-200',
      iconBg: 'bg-pink-500',
      textColor: 'text-pink-800',
      borderColor: 'border-pink-200',
    },
    {
      id: 23,
      letter: "Х",
      title: "Изучаем букву Х",
      description: "Буква русского алфавита - Х",
      words: ["Хомяк", "Хлеб", "Химия", "Холод"],
      images: ["🐹", "🍞", "🧪", "❄️", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "ХНайдите предметы на эту букву",
      letterImage: "🐹",
      bgColor: 'bg-indigo-100 hover:bg-indigo-200',
      iconBg: 'bg-indigo-500',
      textColor: 'text-indigo-800',
      borderColor: 'border-indigo-200',
    },
    {
      id: 24,
      letter: "Ц",
      title: "Изучаем букву Ц",
      description: "Буква русского алфавита - Ц",
      words: ["Цветок", "Цирк", "Царь", "Цыпленок"],
      images: ["🌸", "🎪", "👑", "🐤", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "ЦНайдите предметы на эту букву",
      letterImage: "🌸",
      bgColor: 'bg-teal-100 hover:bg-teal-200',
      iconBg: 'bg-teal-500',
      textColor: 'text-teal-800',
      borderColor: 'border-teal-200',
    },
    {
      id: 25,
      letter: "Ч",
      title: "Изучаем букву Ч",
      description: "Буква русского алфавита - Ч",
      words: ["Черепаха", "Часы", "Чай", "Черный"],
      images: ["🐢", "⏰", "☕", "⚫", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "ЧНайдите предметы на эту букву",
      letterImage: "🐢",
      bgColor: 'bg-cyan-100 hover:bg-cyan-200',
      iconBg: 'bg-cyan-500',
      textColor: 'text-cyan-800',
      borderColor: 'border-cyan-200',
    },
    {
      id: 26,
      letter: "Ш",
      title: "Изучаем букву Ш",
      description: "Буква русского алфавита - Ш",
      words: ["Шар", "Школа", "Шляпа", "Шоколад"],
      images: ["🎈", "🏫", "🎩", "🍫", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "ШНайдите предметы на эту букву",
      letterImage: "🎈",
      bgColor: 'bg-orange-100 hover:bg-orange-200',
      iconBg: 'bg-orange-500',
      textColor: 'text-orange-800',
      borderColor: 'border-orange-200',
    },
    {
      id: 27,
      letter: "Щ",
      title: "Изучаем букву Щ",
      description: "Буква русского алфавита - Щ",
      words: ["Щенок", "Щука", "Щетка", "Щит"],
      images: ["🐶", "🐟", "🪥", "🛡️", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "ЩНайдите предметы на эту букву",
      letterImage: "🐶",
      bgColor: 'bg-emerald-100 hover:bg-emerald-200',
      iconBg: 'bg-emerald-500',
      textColor: 'text-emerald-800',
      borderColor: 'border-emerald-200',
    },
    {
      id: 28,
      letter: "Ъ",
      title: "Изучаем букву Ъ",
      description: "Буква русского алфавита - Ъ",
      words: ["Подъезд", "Объект", "Съемка", "Разъем"],
      images: ["🏢", "📦", "📹", "🔌", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "Ъ Изучаем слова с этим знаком",
      letterImage: "🏢",
      bgColor: 'bg-violet-100 hover:bg-violet-200',
      iconBg: 'bg-violet-500',
      textColor: 'text-violet-800',
      borderColor: 'border-violet-200',
    },
    {
      id: 29,
      letter: "Ы",
      title: "Изучаем букву Ы",
      description: "Буква русского алфавита - Ы",
      words: ["Мыло", "Рыба", "Сыр", "Дым"],
      images: ["🧼", "🐟", "🧀", "💨", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "Ы Найдите слова с этим звуком",
      letterImage: "🧼",
      bgColor: 'bg-sky-100 hover:bg-sky-200',
      iconBg: 'bg-sky-500',
      textColor: 'text-sky-800',
      borderColor: 'border-sky-200',
    },
    {
      id: 30,
      letter: "Ь",
      title: "Изучаем букву Ь",
      description: "Буква русского алфавита - Ь",
      words: ["Медведь", "Олень", "Конь", "Тюлень"],
      images: ["🐻", "🦌", "🐴", "🦭", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "Ь Изучаем слова с этим знаком",
      letterImage: "🐻",
      bgColor: 'bg-rose-100 hover:bg-rose-200',
      iconBg: 'bg-rose-500',
      textColor: 'text-rose-800',
      borderColor: 'border-rose-200',
    },
    {
      id: 31,
      letter: "Э",
      title: "Изучаем букву Э",
      description: "Буква русского алфавита - Э",
      words: ["Эскимо", "Экран", "Этаж", "Эхо"],
      images: ["🍦", "💻", "🏢", "🔊", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "Э Найдите слова с этим звуком",
      letterImage: "🍦",
      bgColor: 'bg-amber-100 hover:bg-amber-200',
      iconBg: 'bg-amber-500',
      textColor: 'text-amber-800',
      borderColor: 'border-amber-200',
    },
    {
      id: 32,
      letter: "Ю",
      title: "Изучаем букву Ю",
      description: "Буква русского алфавита - Ю",
      words: ["Юла", "Юрта", "Южный", "Юмор"],
      images: ["🌀", "🏘️", "🧭", "😄", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "Изучайте слова со звуком Ю",
      letterImage: "🌀",
      bgColor: 'bg-lime-100 hover:bg-lime-200',
      iconBg: 'bg-lime-500',
      textColor: 'text-lime-800',
      borderColor: 'border-lime-200',
    },
    {
      id: 33,
      letter: "Я",
      title: "Изучаем букву Я",
      description: "Буква русского алфавита - Я",
      words: ["Яблоко", "Ящерица", "Язык", "Ягода"],
      images: ["🍎", "🦎", "👅", "🍓", "🎆", "🎨", "📚", "✨", "🎭", "🏆"],
      activity: "Я Найдите слова с этим звуком",
      letterImage: "🍎",
      bgColor: 'bg-green-100 hover:bg-green-200',
      iconBg: 'bg-green-500',
      textColor: 'text-green-800',
      borderColor: 'border-green-200',
    },
  ];

  const openLesson = (lesson) => {
    if (onLessonSelect) {
      onLessonSelect(lesson);
    }
  };

  return (
    <div className="min-h-screen bg-purple-50 py-8">
      <div className="max-w-7xl mx-auto px-6">
        <div className="flex items-center mb-8">
          <button
            onClick={onBack}
            className="bg-purple-400 hover:bg-purple-500 text-white font-bold py-3 px-6 rounded-full text-lg shadow-lg transform hover:scale-105 transition-all duration-200 mr-6"
          >
            ⬅️ Назад
          </button>
          <div className="text-center flex-1">
            <h1 className="text-5xl font-bold text-purple-800 mb-4">🔤 Русские буквы</h1>
            <p className="text-xl text-purple-600">
              Изучение букв русского алфавита - 33 урока
            </p>
          </div>
        </div>

        {/* Карточки уроков */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 max-w-8xl mx-auto">
          {lessons.map((lesson) => (
            <div
              key={lesson.id}
              onClick={() => openLesson(lesson)}
              className={`${lesson.bgColor} rounded-3xl p-6 cursor-pointer transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-xl min-h-[240px] flex flex-col justify-center border-4 ${lesson.borderColor} overflow-hidden`}
            >
              <div className="text-center w-full px-2">
                <div
                  className={`w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center ${lesson.iconBg} text-white shadow-lg relative`}
                >
                  <span className="text-2xl font-bold">{lesson.letter}</span>
                  {lesson.letterImage && (
                    <div className="absolute -top-2 -right-2 text-3xl animate-bounce">
                      {lesson.letterImage}
                    </div>
                  )}
                </div>
                <div className="bg-white bg-opacity-80 rounded-full px-3 py-1 mb-3">
                  <span className={`text-sm font-bold ${lesson.textColor}`}>
                    Урок {lesson.id}
                  </span>
                </div>
                <h3 className={`text-base font-bold ${lesson.textColor} mb-2 break-words leading-tight`}>
                  {lesson.title}
                </h3>
                <p className={`text-xs ${lesson.textColor} opacity-80 break-words leading-tight`}>
                  {lesson.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default RussianLetters;